### PR TITLE
Random string custom charset

### PR DESCRIPTION
**Pull request by norillsa**
### reference
Today's Slack thread to enhance the existing randomString() function to support a conversion from JMeter's own ${__RandomString()} function. I have enhanced the documentation to describe the changes. Additionally, Tom mentioned that an inevitable version change to ks-jslib-utils to 1.2.0 would require additional edits to the documentation. Those changes were made in [PR #5 on ks-jslib-utils](https://github.com/grafana/k6-jslib-utils/pull/5).

### technical explanation
Enhance the existing randomString() function to accept a second string parameter to provide customized charset. Refactor the internal charset to be wrapped in a conditional if statement, for backwards compatibility where a charset was not provided.
Provide a new randomString.js set of tests; leveraging suggestions from Tom and others. 

### other comments
This is my first PR as a contributor to any open source project. Please forgive any mistakes or missed steps in this process. Thank you.

### CODE REVIEW

**Comment by ppcano** [comment]
wow! @norillsa. Thanks a lot for taking care of the docs as well. We'll review it and update the docs when the feature is merged.

**Comment by norillsa** [comment]
I see the failed: 19:25  error  Did you really mean 'charset'?  Vale.Spelling

Since this is my first submission, can you please help me understand: is there some fix I can do? or ...maybe I just wait? :)

**Comment by javaducky** [comment]
@norillsa Probably a matter of just including an update to the `.vale/Vocab/docs/accept.txt` to include `charset` as a valid spelling.

**Comment by ppcano** [comment]
> including an update to the .vale/Vocab/docs/accept.txt to include charset as a valid spelling.

@norillsa, that will fix the linter error.


If you want to test it locally, install [vale](https://github.com/errata-ai/vale) globally and run the command:

```bash
vale --glob='**/{docs,translated-guides/en}/**/*.md' ./src/data/markdown
```

**Comment by norillsa** [comment]
apologies - I fixed up the incorrect author on those commits

**Comment by norillsa** [comment]
@ppcano  - I'm reviewing the 2 conflicts above and I don't recall changing those files at all on my commits - like, they seem to be unrelated to the randomString() function changes. What do you suggest here? Did they come from some other contribution?

**Review by javaducky — CHANGES_REQUESTED** [review]
Marking this as pending changes as we will need version `1.2.0` of the javascript library to actually be released before this is merged.

**Comment by norillsa** [comment]
Okay - I fixed up those other strange commits - which, I'm hoping that was the right thing to do, given I found no references to utils 1.2.0 or randomString() function on those other commits.

**Comment by javaducky** [comment]
My guess is that you were out of sync with the upstream main branch, then when you force-pushed, you caused the conflicts to be there. Of course, you _have_ to use `--force` or the safer `--force-with-lease` if you re-write history as you did to correct the author names.

One of my favorite sayings:
> Rebase is the path to enlightenment.

The rebase would let your changes be applied to the latest on the upstream, grafana:main branch.

**Comment by norillsa** [comment]
Thank you again - I think it's cleaned up, even with some better commit messages now to be clear.

**Comment by javaducky** [comment]
`v1.2.0` has been released now (https://github.com/grafana/k6-jslib-utils/releases/tag/v1.2.0).

**Review by javaducky — APPROVED** [review]

**Pull request merged**
