### PR TITLE
Destructures cloud FAQ

### PR DESCRIPTION
**Pull request by MattDodsonEnglish**
Fixes: https://github.com/grafana/k6-docs/issues/745

- Moves reference information to Cloud reference (along with some other miscellaneous topics)
- PLZs and Troubleshooting to running tests
- Some language fixes (not all)

This moves useful content higher up the doc hierarchy, and splits the content to the places where it's most relevant.
As a side bonus, this extra reference makes it easier for future content additions and restructuring.

**One breaking change**: links to https://k6.io/docs/cloud/cloud-faq/general-questions/ will break. This page got split across three docs, so a redirect for each anchor would be too tricky. 

Before merging, I must:
- [x] Run a link checker on changed pages
- [x] Review images
- [ ] Proofread work
- [x] Check Cloud UI text for FAQ links, fix if needed.

@ppcano I think I can handle this independently, but I'm tagging you just so you see what is incoming. @Vmihajlovic , these changes may move some info that you look at and link to often to other places.

### CODE REVIEW

**Comment by ppcano** [comment]
Some small inputs:

- The `Cloud references` category is similar to `Misc` category on the OSS guides. I suggest testing whether both docs could be consistent in the naming.

- Instead of having a 404 page for the old `cloud-faq/general-question` page, I think it is better to have a redirect to a general page; for example, either the Cloud Docs main page or the `Cloud references` category page.

**Comment by Vmihajlovic** [comment]
Just a few notes on my end as well:

1. I know that we are linking to specific documentation articles directly in the web app, i.e., Performance Insights links
2. not sure if we want to highlight which features are not available by default (similar to Private Load Zones). Namely PDF export and Usage Reports; they are available only in Annual Pro and above. Naturally, this is the current state of things, and updating these references as we change plans/pricing/models in the future might prove to be cumbersome. Perhaps a stop-gap solution would be to link to the pricing page.

**Comment by MattDodsonEnglish** [comment]
> 1. I know that we are linking to specific documentation articles directly in the web app, i.e., Performance Insights links. We should make sure they continue working after we merge these changes.

Great point, Viktor, thanks! I'm going to grep around the cloud repo, and I've added that to the publication checklist. Even if I don't find any breaks this time, more changes are likely to come. 

> Instead of having a 404 page for the old cloud-faq/general-question page, I think it is better to have a redirect to a general page;

Definitely. Should have thought of that. Fixed.

> The Cloud references category is similar to Misc category on the OSS guides. I suggest testing whether both docs could be consistent in the naming.

Great question. Not sure if it's for the scope of this PR, but I support making the OSS docs have a distinct "Reference" section too. However the current "Misc" has a lot more miscellany than just reference.

For the sake of terminology, let's say that reference material is material that readers look at only to check certain values and see examples. A reference just tries to help a reader find information; assumes the reader will know what to do with it.

Let's review:

Misc
- [Usage collection](https://k6.io/docs/misc/usage-collection/) :heavy_check_mark:  Pure reference
[IntelliSense](https://k6.io/docs/misc/intellisense/) :question:  I don't even know what this is! Should this really be on the main docs page? Seems more for integrations.
[Fine tuning OS](https://k6.io/docs/misc/fine-tuning-os/) :x: No, definitely a deep how-to guide or explanation. One of the deepest dives we have. Great article, not reference.
[Archive Command](https://k6.io/docs/misc/archive-command/) :question:  Kind of a mixed reference, how-to, explanation. Not really a reference, because readers will go there to learn, not just to look.
[TypeScript template](https://github.com/k6io/template-typescript) :question:  I don't even know what this is! Should this really be on the main docs page? Seems more for integrations.
[Release notes](https://github.com/grafana/k6/releases) :heavy_check_mark: Pure reference
[Glossary](https://k6.io/docs/misc/glossary/) :heavy_check_mark: Pure reference

**Comment by MattDodsonEnglish** [comment]
I made such a mess here that I'm opting for a clean restart:
https://github.com/grafana/k6-docs/pull/783

**Pull request closed without merging**
