### PR TITLE
Update Prometheus remote-write

### LINKED ISSUE #995: Update the documentation for the Prometheus output
Discussed with @codebien  the following [Prometheus remote write](https://k6.io/docs/results-output/real-time/prometheus-remote-write/) changes:

- move instructions from the extension readme to the documentation
- Include latest dashboards
- docker-compose instructions
- install the dashboard from the [Grafana Directory](https://grafana.com/grafana/dashboards/18002-test-result/)
- ...

### PR DESCRIPTION
**Pull request by codebien**
Closes #995

### CODE REVIEW

**Comment by codebien** [comment]
>install the dashboard from the Grafana Directory

This point is missing, I think we should add it to the doc on grafana.com. @javaducky do you have permission for updating it?

**Comment by javaducky** [comment]
I can update the published dashboard at https://grafana.com/grafana/dashboards/18030-test-result/. Do the screenshots included in the community need to be changed? Wasn't sure if this was just a rename of images.

**Comment by codebien** [comment]
@javaducky Yeah, we should refresh the screenshots also.

**Review by javaducky — APPROVED** [review]
LGTM!

**Pull request merged**
