### PR TITLE
feat(docs): broken links checker

### LINKED ISSUE #334: Add broken link checking to CI for docs and marketing

### PR DESCRIPTION
**Pull request by sashasushko**
I decided to add link checker only on the stage, because (IMHO) command to heavy for every PR.

Also, I added simple regexp for skipping CSS and JS files and completely skipped Google Fonts.

Close #334

### CODE REVIEW

**Comment by sashasushko** [comment]
For PRs we can create more clever logic of testing. For example, we can check links only on a page which was changed. I think it's not so hard to write a bash-script for it.

**Comment by MattDodsonEnglish** [comment]
>Is it possible to make the errors warnings? Or to stop the CI from exiting with a non-zero? Last time I ran the checker we had a bunch to clean up, and some in metadata. I'm not sure if we're ready for links to block.
 
 Hmm now it looks like there are about 250 broken links, and the broken links in the metadata don't show up :shrug: The dream of zero broken links is closer than I thought (at least I change a page title again :laughing: ).

**Comment by bolotskydev** [comment]
Great job! 🔥  I am all up for making lenses focused on pages in delta. Also I wonder if we still need [previous setup](https://github.com/grafana/k6-docs/pull/886/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R29) for broken links check?

**Comment by sashasushko** [comment]
> Is there a way to test what it looks like?

You can switch to this branch and run `npm run check:broken-links -- https://staging.k6.io/docs`. Then wait about 5-10 minutes, and you will see a report like that:
```json
[
    {
      "url": "https://mdr-ci.staging.k6.io/docs/refs/pull/888/merge/get-started/k6-resources/",
      "status": 404,
      "state": "BROKEN",
      "parent": "https://mdr-ci.staging.k6.io/docs/refs/pull/888/merge/get-started/resources/"
    },
    {
      "url": "https://mdr-ci.staging.k6.io/docs/refs/pull/888/merge/using-k6/test-life-cycle",
      "status": 404,
      "state": "BROKEN",
      "parent": "https://mdr-ci.staging.k6.io/docs/refs/pull/888/merge/get-started/running-k6/"
    },
    {
      "url": "https://mdr-ci.staging.k6.io/docs/refs/pull/888/merge/using-k6/options/",
      "status": 404,
      "state": "BROKEN",
      "parent": "https://mdr-ci.staging.k6.io/docs/refs/pull/888/merge/using-k6/k6-options/"
    },
    ...
]
```

**Review by bolotskydev — APPROVED** [review]

**Comment by sashasushko** [comment]
> Why concurrency 10? Just wondering, because I saw that the default is 100

Just "safe value" to avoid 429 error. When we fix all errors like #771 or #763 and completely setup `skip` flag, we can increase it.

**Comment by sashasushko** [comment]
> Is it possible to make the errors warnings? Or to stop the CI from exiting with a non-zero? Last time I ran the checker we had a bunch to clean up, and some in metadata. I'm not sure if we're ready for links to block.

Give me a moment, I will check.

**Comment by sashasushko** [comment]
@MattDodsonEnglish I set up [`continue-on-error`](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idcontinue-on-error) flag for `linkinator` job, it should prevent falling of all workflow

**Review by MattDodsonEnglish — APPROVED** [review]
Awesome! I checked locally and it looked good. I think I'm ready to see how it looks in action, and start iterating--make it faster, add slack reports, etc (just ideas).

 The only thing work I see for now is to make a workflow that checks only files changed in a PR. But I think that could be a separate issue, couldn't it? @sashasushko If you agree and don't see any other work to do for now, I'm happy to merge this and see how it works in action.
 
 Thanks for the work!

**Comment by sashasushko** [comment]
> The only thing work I see for now is to make a workflow that checks only files changed in a PR. But I think that could be a separate issue, couldn't it?

Yep

> If you agree and don't see any other work to do for now, I'm happy to merge this and see how it works in action.

Wait a minute. I'll revert last commit.

**Pull request merged**
