### PR TITLE
Add xk6-fasthttp extension

### PR DESCRIPTION
**Pull request by domsolutions**
## What?

New extension related to discussion on https://github.com/grafana/k6/issues/3471

## Checklist

Please fill in this template:
- [x] I have used a meaningful title for the PR.
- [x] I have described the changes I've made in the "What?" section above.
- [x] I have performed a self-review of my changes.
- [x] I have run the `make docs` command locally and verified that the changes look good.

Select one of these and delete the others:

If updating the documentation for the most recent release of k6: 
- [x] I have made my changes in the `docs/sources/next` folder of the documentation.
- [x] I have reflected my changes in the `docs/sources/v{most_recent_release}` folder of the documentation.
- [ ] I have reflected my changes in the relevant (*e.g.*  when correcting a documentation error) folders of the previous k6 versions of the documentation.

If updating the documentation for the next release of k6:
- [ ] I have made my changes in the `docs/sources/next` folder of the documentation.

### CODE REVIEW

**Comment by heitortsergent** [comment]
Hi @domsolutions! Thanks for opening the PR! I added @javaducky and @joanlopez here for review based on the conversation on the other k6 issue. :)

Would you mind updating the extension file that's in the `docs/sources` folder? That's the source for the new docs that are live on [Grafana](https://grafana.com/docs/k6/latest/), you can see [this other PR](https://github.com/grafana/k6-docs/pull/1452/files) for reference as well.

**Review by javaducky — CHANGES_REQUESTED** [review]
@domsolutions, thank you for the contribution and for creating a new extension!

We're still in the process of migrating our documentation, so sadly, we'll need some additional updates before we can merge this. The changes you have in `extensions.json` is fine, but it only affects docs hosted on the [k6.io site](https://k6.io/docs/extensions/get-started/explore/).

We'll need similar additions to affect the docs for k6 v0.48 (latest) and future versions by adding to the following:
- [docs/sources/v0.48.x/extensions/explore.md](docs/sources/v0.48.x/extensions/explore.md)
- [docs/sources/next/extensions/explore.md](docs/sources/next/extensions/explore.md)

👉  Please be sure to maintain the alphabetic sorting when adding your extension.

**Comment by domsolutions** [comment]
> @domsolutions, thank you for the contribution and for creating a new extension!
> 
> We're still in the process of migrating our documentation, so sadly, we'll need some additional updates before we can merge this. The changes you have in `extensions.json` is fine, but it only affects docs hosted on the [k6.io site](https://k6.io/docs/extensions/get-started/explore/).
> 
> We'll need similar additions to affect the [Grafana docs](https://grafana.com/docs/k6/latest/extensions/explore/) for k6 v0.48 (latest) and future versions by adding to the following:
> 
> * [docs/sources/v0.48.x/extensions/explore.md](https://github.com/grafana/k6-docs/blob/main/docs/sources/v0.48.x/extensions/explore.md)
> * [docs/sources/next/extensions/explore.md](https://github.com/grafana/k6-docs/blob/main/docs/sources/next/extensions/explore.md)
> 
> 👉 Please be sure to maintain the alphabetic sorting when adding your extension.

No problem! all done

**Review by javaducky — APPROVED** [review]
Awesome! Thanks for the updates @domsolutions!

**Comment by domsolutions** [comment]
Hi @javaducky 

I can see the extension on https://grafana.com/docs/k6/latest/extensions/explore/ but can't see it listed on https://k6.io/docs/extensions/get-started/explore/ ?

**Comment by mstoykov** [comment]
k6.io/docs is deprecated as per the message in the top and all future doc updates or only happening in the grafana docs. 

v0.48.0 (current release) was the one this was made, so it is very likely in the near future this will be even more noticeable.

**Pull request merged**
