### PR TITLE
Remove the deprecated `k6/experimental/tracing`

### PR DESCRIPTION
**Pull request by mstoykov**
## What?

Documentation changes around https://github.com/grafana/k6/pull/3855

## Checklist

- [ ] I have used a meaningful title for the PR.
- [ ] I have described the changes I've made in the "What?" section above.
- [ ] I have performed a self-review of my changes.
- [ ] I have run the `npm start` command locally and verified that the changes look good.

- [ ] I have made my changes in the `docs/sources/next` folder of the documentation.
- [ ] I have reflected my changes in the `docs/sources/v{most_recent_release}` folder of the documentation.
- [ ] I have reflected my changes in the relevant folders of the two previous k6 versions of the documentation (if still applicable to previous versions).

- [ ] I have made my changes in the `docs/sources/next` folder of the documentation.

### CODE REVIEW

**Review by inancgumus — COMMENTED** [review]
I don't know about this project a lot, but I wonder if we do not need to remove the other references.

- https://github.com/grafana/k6-docs/blob/dde5a2a4718a640f79c81b0baf85d13411b1e1d6/src/data/markdown/docs/02%20javascript%20api/07%20k6-experimental.md#L14
- https://github.com/grafana/k6-docs/blob/dde5a2a4718a640f79c81b0baf85d13411b1e1d6/src/data/markdown/translated-guides/en/07%20Testing%20Guides/02%20Automated%20performance%20testing.md#L260

and so on.

**Comment by heitortsergent** [comment]
I think it makes sense to remove the other references as well @inancgumus. We can also include aliases in the jslib utils pages so if people try to access those pages they get redirected to the correct library instead of seeing a 404.

Let me know if you want me to take care of this @mstoykov and I can make the changes in this PR. 🙏

**Comment by mstoykov** [comment]
Good catch @inancgumus ... I think I just looked into `next` and not the other parts of the docs.

@heitortsergent I will be glad if you take care of this :bow:

**Comment by heitortsergent** [comment]
Actually, I looked into the other references and I think we can keep them. Since this is being removed in the next version of k6, it makes sense that we just remove them from the `next` folder. :)

I added aliases from the deleted pages to the `http-instrumentation-tempo` module, so if anyone had links with `latest` in it they should be redirected to the correct page and not see a 404.

**Review by heitortsergent — APPROVED** [review]

**Comment by oleiade** [comment]
Merging this to move forward with the release process 🙇‍♂️

**Pull request merged**
