### PR TITLE
Clean experimental gRPC references

### PR DESCRIPTION
**Pull request by olegbespalov**
## What?

This cleans a few left over references to experimental gRPC.

## Checklist

- [x] I have used a meaningful title for the PR.
- [x] I have described the changes I've made in the "What?" section above.
- [x] I have performed a self-review of my changes.
- [x] I have run the `npm start` command locally and verified that the changes look good.

- [x] I have made my changes in the `docs/sources/next` folder of the documentation.
- [x] I have reflected my changes in the `docs/sources/v{most_recent_release}` folder of the documentation.
- [ ] I have reflected my changes in the relevant folders of the two previous k6 versions of the documentation (if still applicable to previous versions).

### CODE REVIEW

**Review by heitortsergent — COMMENTED** [review]
@olegbespalov the changes look good!
 
Just wanna double-check with you, do we want to only update the `next` folder, or do we want to update the `v0.50.x` as well?

I also found this one mention on the metrics reference file, do we need to remove that as well? https://github.com/grafana/k6-docs/blob/main/docs/sources/next/using-k6/metrics/reference.md?plain=1#L106

**Comment by olegbespalov** [comment]
Hey @heitortsergent !

Yes, we do want to adjust them both. In v0.50, it was leftover, and the next step is to stop producing this "bug" anymore.

**Review by heitortsergent — APPROVED** [review]
:shipit:

**Comment by heitortsergent** [comment]
@olegbespalov I see those references have already been removed from the `v0.50.x` folder, sorry about that! LGTM! :shipit:

**Pull request merged**
