### PR TITLE
Update of the "Load Zones" link in the "Could options" document

### PR DESCRIPTION
**Pull request by ovenal**
## What?

"Load Zones" link leads to an incorrect page, it should lead to "Load Zones" page.

### CODE REVIEW

**Comment by heitortsergent** [comment]
Hi @ovenal! Thanks for catching that error. I'd be happy to merge it if you're ok with signing the CLA. 😄

**Comment by ovenal** [comment]
> Hi @ovenal! Thanks for catching that error. I'd be happy to merge it if you're ok with signing the CLA. 😄

Yes, sure, just give me a hint how to sign the CLA - I’ve never done it :)

**Comment by ovenal** [comment]
Thanks, done.

**Review by heitortsergent — APPROVED** [review]

**Comment by heitortsergent** [comment]
Thanks for your contribution, @ovenal! 🚀

**Pull request merged**
