### PR TITLE
Added `DescriptionList` component

### PR DESCRIPTION
**Pull request by Den-Bratchikov**
**Describe what changes this pull request brings**
This pull request adds `DefinitionList` component. The objective is to have an ability to provide the description of names or terms by presenting them in a description list. 

**Changes**:
- introduced `DescriptionList` component
- `Glossary` page rewrite using new component
- extended `CONTRIBUTING_FILE_FORMATS` with the new component description

_[Read more on component API and constraints](https://github.com/grafana/k6-docs/blob/definition-list/CONTRIBUTING_FILE_FORMAT.md)_

**Steps to test:**
Explore the modified [Glossary](https://mdr-ci.staging.k6.io/docs/refs/pull/740/merge/misc/glossary/) page

**Screenshots**

<details>
<summary>DescriptionList example on Glossary page</summary>

definition-list

</details>

Closes: #694

### CODE REVIEW

**Comment by MattDodsonEnglish** [comment]
Thanks for getting this work in! I know it's still a work in progress, but if I could make a few comments from a user's perspective.

First of all, I should have mentioned where this would be immediately put to use: [the k6 Glossary](https://k6.io/docs/misc/glossary/) . It's just a long list of terms, with multi-paragraph definitions.

- However, note that each term has an anchor, so it's important the `<dt>` will have an `id` attribute, so it's sluggable.
  
- As it's a list of terms, the `<DescriptionList>` function must support multiple items (just making sure).

- From an author's perspective, the syntax proposed is a little flat. Would it be possible to set off each definition with a `-`? This is small, but a little hierarchy will help writers stay visually organizaed. And I don't know whether the white space is optional, but removing it makes the syntax more compact.

  Instead of this:
   ```markdown
   
   Term:
   
   Definition one
   
   Definition two
   
   ```

  I prefer this:

   ```
  Term:
  - Definition 1
  - Definition 2
  ```
  Or the syntax from extended markdown is fine too https://www.markdownguide.org/extended-syntax#definition-lists.

* Currently, I can't make it work in this fork. I tried a few syntax combinations, but they all got this error. Again, I know it's WiP, but just commenting.
image

**Comment by bolotskydev** [comment]
Hey @MattDodsonEnglish, you are right about this PR being in WIP mode) Please, assume nothing of draft PRs from our side: they may not work, they may not be implemented correctly, they may be out of sync with the initial task request.

For sure the current state has confused you, mainly because I was too lazy to make the review transparent by leaving comments in this very thread and pointed out all the problems with syntax, content editor experience and implementation to @Den-Bratchikov on a call this morning 😓 .

The comments you've left are absolutely valid and already being worked on 💯 I will ping you additionally once we're done with this one 😉

**Comment by bolotskydev** [comment]
@MattDodsonEnglish , it is almost there! Tomorrow I'll do the last mile - PR description, documentation, minor style adjustment, but as of now you can peek at [Glossary](https://mdr-ci.staging.k6.io/docs/refs/pull/740/merge/misc/glossary/) page you've mentioned before to see the component in action, if you curious 😉 . The core logic is there and the markup is fully WCAG compliant. Anchors are also in place.

**Comment by bolotskydev** [comment]
@MattDodsonEnglish we are good to go 👌

**Comment by MattDodsonEnglish** [comment]
Looking good! And very nice, writer-friendly syntax. Thanks also for adding the great documentation.

Sorry, I was a over-zealous when I commented before being requested for review :grimacing: It was enthusiasm for the feature, as this will come in handy in all sorts of places.

:+1:

**Comment by bolotskydev** [comment]
Nvm, glad you've liked it!

**Pull request merged**
