### PR TITLE
feat: add Tooltip component for Markdown content

### LINKED ISSUE #648: Show tooltips
xk6-browser is still in development, and we want to display a _"Not implemented"_ tooltip for the missing features. Some of these features are never planned, some are in the planning, and some are in development.

For the never-planned ones, we want to display a tooltip as follows (when mouse hovered on it):

<img width="865" alt="Screen Shot 2022-04-28 at 13 39 13" src="https://user-images.githubusercontent.com/621232/165735021-a681e1fc-609e-4882-b07a-db820fa861fa.png">

So we added a tooltip using a `span` tag as follows:

```
| Option                                                              | Type    | Description                                                                                                                                                                                                                                                                                                                                                     |
| ------------------------------------------------------------------- | ------- | --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| acceptDownloads                                                     | boolean | Whether to automatically download files. Defaults to `true`.                                                                                                                                                                                                                                                                                                    |
| <span title="Not implemented">❌</span> baseURL                     | string  | The base URL to use for all relative URLs. For example: `/open-source/` will be converted to `https://k6.io/open-source/` if `baseURL` is set to `https://k6.io`.                                                                                                                                                                                               |
```

For the ones that are in the planning and development stages, we want to display the same tooltip but also let users click on it to see the relevant Github issue:

<img width="942" alt="Screen Shot 2022-04-28 at 13 40 34" src="https://user-images.githubusercontent.com/621232/165735247-18450d58-ba79-4773-a372-830a4c014595.png">

So we added a tooltip with a link as follows:

```
| Option                                                              | Type    | Description                                                                                                                                                                                                                                                                                                                                                     |
| ------------------------------------------------------------------- | ------- | --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| [❌](https://github.com/grafana/xk6-browser/issues/103) recordVideo | object  | Activates video recording for the context's pages.                                                                                                                                                                                                                                                                                                              |
```

As you can see, our solution is not optimal as `span`s and links occupy a lot of space in the Markdown table and break its formatting by shifting all the columns to the right. So, we thought of adding a JS widget to make this convenient for us.

### PR DESCRIPTION
**Pull request by SilencerWeb**
This PR adds 3 components in order to resolve #648:
1. `Tooltip` — just a general tooltip that can be used across docs
2. `BNIT` — xk6-browser "Not Implemented" tooltip
3. `BWIPT` — xk6-browser "Work in Progress" tooltip

Usage example:
```jsx
// BNIT *without* link to the issue
<BNIT/>

// BNIT *with* link to the issue
<BNIT id="103"/>


// BWIPT *without* link to the issue
<BWIPT/>

// BNIT *with* link to the issue
<BWIPT id="103"/>
```

TODO:
- [x] Remove examples before merging PR

### CODE REVIEW

**Comment by imiric** [comment]
That sounds good @SilencerWeb! (Hi, I'm another xk6-browser dev working on these same docs :slightly_smiling_face:)

If we could have the component scoped only to the xk6-browser docs, that would be even better. Or if there's a way of initializing a component with predefined values once per page, so that we could set a URL prefix or icon to use, then it could be useful globally.

Otherwise `NIT` for this use case, and maybe `WIPT` for a `WorkInProgressTooltip` that will show 🚧 would be good as well.

**Comment by inancgumus** [comment]
I skimmed the commits, and it's looking good to me 👍

**Comment by inancgumus** [comment]
I skimmed the commits, and it looks good to me 👍

**Comment by SilencerWeb** [comment]
@inancgumus we can add a generic component that you guys will be able to use in order to create such custom reusable tooltips, I'm just not sure if we 100% need it right now 🤔

**Comment by inancgumus** [comment]
Sure, the current one fits our needs, WDYT @imiric?

**Comment by inancgumus** [comment]
Hey @SilencerWeb, can you merge this? We can't wait to use it!

**Comment by SilencerWeb** [comment]
@inancgumus please let me know if anything else will be needed!

**Pull request merged**
