### PR TITLE
Added couchbase performance test extension

### PR DESCRIPTION
**Pull request by thotasrinath**
Created an extension to test perfomance on couchbase. Thanks

### CODE REVIEW

**Comment by thotasrinath** [comment]
Hi @javaducky, Please review the PR.. Please let me know if any changes needed

**Review by javaducky — COMMENTED** [review]
Looking at [xk6-couchbase](https://github.com/thotasrinath/xk6-couchbase), we require that there be a license added to the project.

**Comment by thotasrinath** [comment]
@javaducky, I have added license.. Thanks

**Review by javaducky — APPROVED** [review]
LGTM! Thank you!

**Pull request merged**
