### PR TITLE
format lists with columns

### PR DESCRIPTION
**Pull request by robbymilo**
## What?

Formats requested lists with the new `column-list` shortcode.

## Checklist

- [x] I have used a meaningful title for the PR.
- [x] I have described the changes I've made in the "What?" section above.
- [x] I have performed a self-review of my changes.
- [ ] I have run the `npm start` command locally and verified that the changes look good.

- [x] I have made my changes in the `docs/sources/next` folder of the documentation.
- [x] I have reflected my changes in the `docs/sources/v{most_recent_release}` folder of the documentation.
- [x] I have reflected my changes in the relevant folders of the two previous k6 versions of the documentation (if still applicable to previous versions).

- [x] I have made my changes in the `docs/sources/next` folder of the documentation.

## Related PR(s)/Issue(s)

for https://github.com/grafana/website/issues/20059

### CODE REVIEW

**Comment by heitortsergent** [comment]
Thanks @robbymilo, I think this new shortcode looks really neat!

I did try to build this locally and got this error message:

```
Error: error building site: assemble: "/hugo/content/docs/k6/next/misc/glossary.md:16:1": failed to extract shortcode: template for shortcode "column-list" not found
````

Do we need to wait to merge this still, or will it work once it's deployed?

**Comment by jdbaldry** [comment]
We still need to release a new version of the `grafana/docs-base` image with the shortcode baked in. It should work if you run with `make docs DOCS_IMAGE=grafana/docs-base:nightly`

**Comment by jdbaldry** [comment]
Promoted the latest image from the nightly image so this should be good to merge now @heitortsergent

**Comment by heitortsergent** [comment]
Thanks @jdbaldry and @robbymilo! :shipit:

**Pull request merged**
