### PR TITLE
Publish technical documentation to the website repository

### PR DESCRIPTION
**Pull request by jdbaldry**
Each commit in this PR should be meaningful in isolation.

This PR cannot be merged until the linting errors reported by the `doc-validator` workflow are resolved. If any of the errors are unclear or if you need any guidance in resolving the linting errors, don't hesitate to ask and I will try and incorporate the feedback into the linting rules for the future.

### CODE REVIEW

**Comment by jdbaldry** [comment]
Makes sense to me, would you like me to rebase on your branch?

**Comment by ppcano** [comment]
Yes, please.

**Comment by jdbaldry** [comment]
All done :)

**Comment by ppcano** [comment]
Can I merge it now to that branch?

**Comment by jdbaldry** [comment]
Sure!

**Pull request merged**
