### PR TITLE
Archive v0.35 documentation and switch the latest version

### PR DESCRIPTION
**Pull request by olegbespalov**
!!! This PR is waiting for the v0.36

Archiving the v0.35 documentation and switching to a new version.

TODO(@olegbespalov): before merging check if the master contains no new commits to the parts that should be archived

### CODE REVIEW

**Review by codebien — COMMENTED** [review]
LGTM

/cc @imiric if you plan to write the doc for `test.abort()`

**Review by na-- — APPROVED** [review]
LGTM, though I am not sure if anything else that was recently merged in master needs to be updated here before we merge this?

**Comment by MStoykov** [comment]
> I am not sure if anything else that was recently merged in master needs to be updated here before we merge this?

checked all the changes are *not* on versioned files so we are clear

**Review by MStoykov — APPROVED** [review]

**Comment by olegbespalov** [comment]
Agreed with @MStoykov

```bash
git diff origin/feat/archive-v0.35 origin/main src/data/markdown/docs/02\ javascript\ api/* | wc -l
0
```

Going to merge

**Pull request merged**
