### PR TITLE
fix: linkinator CI config

### PR DESCRIPTION
**Pull request by sashasushko**
Until I figure out what the problem is with the config file for the linkinator action - https://github.com/JustinBeckwith/linkinator-action/issues/136 - I passed the config directly to workflow.

### CODE REVIEW

**Comment by sashasushko** [comment]
By the way @MattDodsonEnglish because we use GitHub `${{ serets }}` for storing stage server URL, it will be hidden in output:
Снимок экрана 2022-11-16 в 12 10 16

This asterics:
```text
Error: [404] https://***/docs/results-output/custom-summary
                     ^^^
```

Also, because of `${{ serets }}` I can't set up the next workflow job to pretify output:
Снимок экрана 2022-11-16 в 12 09 27

So, the question is - can we move the stage server URL from `${{ serets }}` to public `${{ env }}`?

**Comment by MattDodsonEnglish** [comment]
Thanks for this, and thanks for making the upstream issue. The biggest project that I know used this is bootstrap. Their config is also directly in the action:

 https://github.com/twbs/bootstrap/blob/1a33235adce370dcf36c96d9509e7ce64beaf660/.github/workflows/docs.yml#L41


Can't imagine a problem with moving the staging variable from secrets; that seems better anyway. But I will double check to be sure.

**Comment by sashasushko** [comment]
> Can't imagine a problem with moving the staging variable from secrets; that seems better anyway. But I will double check to be sure.

Cool 👍 I'll be waiting news from you

**Comment by ppcano** [comment]
>  can we move the stage server URL from ${{ serets }} to public ${{ env }}?

@sashasushko I don't see any problem moving this key as a environment variable. Go ahead, thanks!

**Review by MattDodsonEnglish — APPROVED** [review]

**Comment by sashasushko** [comment]
@MattDodsonEnglish @ppcano cool 💪 Thanks. One more thing – can someone of you provide to me value of this variable `STAGING_CI_MAIN_URL`?

**Comment by sashasushko** [comment]
I guess it's `staging.k6.io`, but who knows? :-)

**Comment by ppcano** [comment]
@sashasushko staging env is under https://staging.k6.io/

Not sure the real value atm, but you can guess by how the app is building the final URL. Let me know if you need the confirmation.

**Comment by MattDodsonEnglish** [comment]
Thanks for this fix, Sasha. The UX improvement is much better than I thought.

The logs are much lighter, and it's really nice being able to select the links from the logs and go right to the page where the break is:
https://github.com/grafana/k6-docs/actions/runs/3479124301/jobs/5817526912

**Comment by sashasushko** [comment]
You're welcome 🤝 

And... We can do it a little bit better 😄 For example, if we'll format output as `JSON`:
Снимок экрана 2022-11-16 в 18 35 10
_it's my website links, just for testing_

But in that case, we have to use [GitHub Action Artifacts](https://docs.github.com/en/enterprise-cloud@latest/rest/actions/artifacts). That means the report will be attached for each workflow run:
Снимок экрана 2022-11-16 в 18 38 11

**Pull request merged**
