### PR TITLE
move k6 browser documentation around

### PR DESCRIPTION
**Pull request by mdcruz**
This PR moves the k6 browser documentation around now that it's an experimental module. The k6 browser guides have been moved to the guides section, and the API has been moved to the javascript API section.

k6 browser guide:
Screenshot 2023-03-14 at 15 03 50

k6 browser API:
Screenshot 2023-03-14 at 14 29 22

This also removes the "k6 browser" on the top-level menu.

Because there are three instances of "browser" as part of the k6 browser API, I had to rename the following to make it work under the structure of the k6-experimental docs:
1. https://k6.io/docs/javascript-api/k6-browser/api/browser/ -> https://mdr-ci.staging.k6.io/docs/refs/pull/1081/merge/javascript-api/k6-experimental/browser/browser-class/
2. https://k6.io/docs/javascript-api/k6-browser/api/browsercontext/browser/ -> https://mdr-ci.staging.k6.io/docs/refs/pull/1081/merge/javascript-api/k6-experimental/browser/browsercontext/browser-instance/

### CODE REVIEW

**Comment by mdcruz** [comment]
> Hi @mdcruz, fixed preserving scroll position for sidebar, please review

Hi @yasell, thanks for this! I can confirm that the scroll position issue has now been fixed. The other issue that I raised as part of https://github.com/grafana/k6-docs/issues/1082 is still outstanding. Let me know if you need more information, but essentially, the menu does not collapse when opened.

1. When I scroll down a page and click the menu to expand, I am redirected back to the top of the page, which could be better because I would need to scroll back down again. ✅ **Fixed**
2. When I try to collapse the menu that I opened, the menu does not collapse. To collapse the menu, I have to expand another menu. ❌ **Still an issue**

**Comment by yasell** [comment]
@mdcruz, fixed, please try to collapse the opened menu with the arrow button

**Comment by mdcruz** [comment]
> > 
> 
> Yes, that's how it works, because the collapse item is a link. When we click on it, we go to that page instead of collapsing the menu.
> 
> Screenshot 2023-03-21 at 18 58 24
> 
> cc @bolotskydev, should we separate the link and the collapse button in this case ?



> @mdcruz, fixed, please try to collapse the opened menu with the arrow button. But first, please resolve conflicts to update preview

Hi @yasell. I have done more testing today, and looks like the collapse issue is fixed. But, when I click an item, my view gets redirected back to the top of the page again. You can find the video recording here.


https://user-images.githubusercontent.com/10811379/227298960-559d7c51-628f-4a9c-b2ab-9c4d20cf3162.mov

**Comment by yasell** [comment]
Hi @mdcruz! Fixed, please review

**Comment by mdcruz** [comment]
> Hi @mdcruz! Fixed, please review

Hi @yasell thank you for the fix! I can still see some issues with the UX as seen in the video I have attached below.

https://user-images.githubusercontent.com/10811379/227920277-d0fbe11c-805a-4ece-9a56-0b33cea722d1.mov

When I scroll down the page, and click on a side menu, the main content's view is also fixed. This means that I have to scroll up to read the content. 

Basically, what we want is for the side menu to be fixed while the main content is always redirected to the top. I'm sorry for not communicating this well!

**Comment by yasell** [comment]
Hi @mdcruz, I've made a sidebar scrollable and the content of the pages is always redirected to the top. Please resolve conflicting files and check if the result is as expected.

**Comment by yasell** [comment]
Hi @mdcruz, thanks for your report, the problem was indeed in the big lists.

I found a solution and the latest commit fixes the problem. Please merge the conflicting files and check the result.

Hope everything goes well 🙌

**Comment by mdcruz** [comment]
> Hi @mdcruz, thanks for your report, the problem was indeed in the big lists.
> 
> I found a solution and the latest commit fixes the problem. Please merge the conflicting files and check the result.
> 
> Hope everything goes well 🙌

Hi @yasell I tested locally and it works like a charm 🥇 Thank you so much!

**Review by ankur22 — APPROVED** [review]
LGTM

**Review by ppcano — APPROVED** [review]

**Review by ka3de — APPROVED** [review]
LGTM :clap:

**Pull request merged**
