### PR TITLE
Add icon for external links

### PR DESCRIPTION
**Pull request by yasell**
This PR adds an icon to external links,
for example –> https://mdr-ci.staging.k6.io/docs/refs/pull/1098/merge/get-started/installation/

### CODE REVIEW

**Comment by MattDodsonEnglish** [comment]
I've clicked through and I think it looks great!


image

**Comment by ppcano** [comment]
@MattDodsonEnglish looks great. Go ahead!

**Comment by MattDodsonEnglish** [comment]
I did discover a bug that happens when the text is imported from an external repo. This is such an extreme edge case that I'm not much worried about it.


image


image

**Comment by MattDodsonEnglish** [comment]
I did discover a bug that happens when the text is imported from an external repo. This is such an extreme edge case that I'm not much worried about it. I'll make a separate issue.


image


image

**Comment by MattDodsonEnglish** [comment]
Sorry for double posting; GitHub's acting a little funny today.

**Pull request merged**
