### PR TITLE
Update k6 browser docs to align with k6 v0.44.0 release

### PR DESCRIPTION
**Pull request by mdcruz**
Once we release k6 v0.44.0, we need to update k6 browser documentation to reflect the following new changes:
- Convert `locator.click()` to use await keyword
- Document `browserContext.addCookies()`
- Document Google Web Vitals

This PR covers the following issues:

https://github.com/grafana/k6-docs/issues/1126
https://github.com/grafana/k6-docs/issues/1127
https://github.com/grafana/k6-docs/issues/1128
https://github.com/grafana/k6-docs/issues/1078

### CODE REVIEW

**Comment by immavalls** [comment]
https://github.com/grafana/k6-docs/issues/1078 lgtm @mdcruz

**Review by ka3de — COMMENTED** [review]
Awesome @mdcruz ! :clap: 

Just a couple of comments.
I believe we are missing the `BrowserContext.addCookie()` entry in the `BrowserContext` methods table [here](https://github.com/grafana/k6-docs/blob/32dddffb11dc04a8d318052c9e885ae5a1a715c6/src/data/markdown/docs/30%20k6-browser/02%20API/02%20BrowserContext.md?plain=1#L13-L15). Although it is present and reachable from the left sidebar.

Also, should we merge the PRs #1114 and #1091 in this branch to group the doc changes for the v0.44.0 version? Or will we merge them independently?

**Comment by mdcruz** [comment]
> Awesome @mdcruz ! 👏
> 
> Just a couple of comments. I believe we are missing the `BrowserContext.addCookie()` entry in the `BrowserContext` methods table [here](https://github.com/grafana/k6-docs/blob/32dddffb11dc04a8d318052c9e885ae5a1a715c6/src/data/markdown/docs/30%20k6-browser/02%20API/02%20BrowserContext.md?plain=1#L13-L15). Although it is present and reachable from the left sidebar.
> 
> Also, should we merge the PRs #1114 and #1091 in this branch to group the doc changes for the v0.44.0 version? Or will we merge them independently?

Ah, yes I forgot! I will add it to the table 👍 
Merging PRs #1114 and #1091 makes sense to me. Can you help with those, please? Thanks!

**Comment by ka3de** [comment]
> Merging PRs https://github.com/grafana/k6-docs/pull/1114 and https://github.com/grafana/k6-docs/pull/1091 makes sense to me. Can you help with those, please? Thanks!

Yes, will merge them both here then :+1:

**Review by ka3de — APPROVED** [review]
LGTM.

**Review by ankur22 — APPROVED** [review]
👏 Thanks for these changes, especially around web vitals 🙌! LGTM!

**Pull request merged**
